apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opencti-allow-web-ingress
  namespace: opencti
spec:
  podSelector:
    matchLabels:
      app: opencti
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
