apiVersion: v1
kind: Secret
metadata:
  name: opencti-secrets
  namespace: opencti
type: Opaque
stringData:
  OPENCTI_ADMIN_EMAIL: "admin@example.com"
  OPENCTI_ADMIN_PASSWORD: "REPLACE_ME"
  OPENCTI_ADMIN_TOKEN: "REPLACE_WITH_UUID"
  OPENCTI_ENCRYPTION_KEY: "REPLACE_WITH_BASE64_KEY"
  MINIO_ROOT_USER: "REPLACE_ME"
  MINIO_ROOT_PASSWORD: "REPLACE_ME"
  RABBITMQ_DEFAULT_USER: "REPLACE_ME"
  RABBITMQ_DEFAULT_PASS: "REPLACE_ME"
  VIRUSTOTAL_TOKEN: "REPLACE_ME"
